### ISSUE TITLE
cmdstanr

### ISSUE THREAD

**Issue by amynang** [ASKurz/Statistical_Rethinking_2_with_rstan#2]
Sorry if this is annoying, but since you are "only" three days in, would you consider switching to Statistical_Rethinking_2_with_cmdstanr instead? Cmdstan tracks Stan updates more tightly and then the speed difference is not negligible. I guess in many way the differences will be minor but some of the post-processing stuff may be different, so it would be amazing to have examples.

**Comment by ASKurz** [comment]
Only kicking and screaming. I've never liked cmdstanr.

**Comment by amynang** [comment]
:smiling_face_with_tear:  fair enough
